package com.course.mapper;

import com.course.pojo.RolPriv;
import com.course.pojo.RolPrivExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RolPrivMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rol_priv
     *
     * @mbg.generated Fri Apr 05 23:30:20 CST 2019
     */
    long countByExample(RolPrivExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rol_priv
     *
     * @mbg.generated Fri Apr 05 23:30:20 CST 2019
     */
    int deleteByExample(RolPrivExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rol_priv
     *
     * @mbg.generated Fri Apr 05 23:30:20 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rol_priv
     *
     * @mbg.generated Fri Apr 05 23:30:20 CST 2019
     */
    int insert(RolPriv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rol_priv
     *
     * @mbg.generated Fri Apr 05 23:30:20 CST 2019
     */
    int insertSelective(RolPriv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rol_priv
     *
     * @mbg.generated Fri Apr 05 23:30:20 CST 2019
     */
    List<RolPriv> selectByExample(RolPrivExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rol_priv
     *
     * @mbg.generated Fri Apr 05 23:30:20 CST 2019
     */
    RolPriv selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rol_priv
     *
     * @mbg.generated Fri Apr 05 23:30:20 CST 2019
     */
    int updateByExampleSelective(@Param("record") RolPriv record, @Param("example") RolPrivExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rol_priv
     *
     * @mbg.generated Fri Apr 05 23:30:20 CST 2019
     */
    int updateByExample(@Param("record") RolPriv record, @Param("example") RolPrivExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rol_priv
     *
     * @mbg.generated Fri Apr 05 23:30:20 CST 2019
     */
    int updateByPrimaryKeySelective(RolPriv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rol_priv
     *
     * @mbg.generated Fri Apr 05 23:30:20 CST 2019
     */
    int updateByPrimaryKey(RolPriv record);
}