package com.course.mapper;

import com.course.pojo.StudentRole;
import com.course.pojo.StudentRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StudentRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_role
     *
     * @mbg.generated Fri Apr 05 23:30:20 CST 2019
     */
    long countByExample(StudentRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_role
     *
     * @mbg.generated Fri Apr 05 23:30:20 CST 2019
     */
    int deleteByExample(StudentRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_role
     *
     * @mbg.generated Fri Apr 05 23:30:20 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_role
     *
     * @mbg.generated Fri Apr 05 23:30:20 CST 2019
     */
    int insert(StudentRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_role
     *
     * @mbg.generated Fri Apr 05 23:30:20 CST 2019
     */
    int insertSelective(StudentRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_role
     *
     * @mbg.generated Fri Apr 05 23:30:20 CST 2019
     */
    List<StudentRole> selectByExample(StudentRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_role
     *
     * @mbg.generated Fri Apr 05 23:30:20 CST 2019
     */
    StudentRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_role
     *
     * @mbg.generated Fri Apr 05 23:30:20 CST 2019
     */
    int updateByExampleSelective(@Param("record") StudentRole record, @Param("example") StudentRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_role
     *
     * @mbg.generated Fri Apr 05 23:30:20 CST 2019
     */
    int updateByExample(@Param("record") StudentRole record, @Param("example") StudentRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_role
     *
     * @mbg.generated Fri Apr 05 23:30:20 CST 2019
     */
    int updateByPrimaryKeySelective(StudentRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_role
     *
     * @mbg.generated Fri Apr 05 23:30:20 CST 2019
     */
    int updateByPrimaryKey(StudentRole record);
}