package com.course.mapper;

import com.course.pojo.Userlogin;
import com.course.pojo.UserloginExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserloginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlogin
     *
     * @mbg.generated Mon Apr 15 15:00:47 CST 2019
     */
    long countByExample(UserloginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlogin
     *
     * @mbg.generated Mon Apr 15 15:00:47 CST 2019
     */
    int deleteByExample(UserloginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlogin
     *
     * @mbg.generated Mon Apr 15 15:00:47 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlogin
     *
     * @mbg.generated Mon Apr 15 15:00:47 CST 2019
     */
    int insert(Userlogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlogin
     *
     * @mbg.generated Mon Apr 15 15:00:47 CST 2019
     */
    int insertSelective(Userlogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlogin
     *
     * @mbg.generated Mon Apr 15 15:00:47 CST 2019
     */
    List<Userlogin> selectByExample(UserloginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlogin
     *
     * @mbg.generated Mon Apr 15 15:00:47 CST 2019
     */
    Userlogin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlogin
     *
     * @mbg.generated Mon Apr 15 15:00:47 CST 2019
     */
    int updateByExampleSelective(@Param("record") Userlogin record, @Param("example") UserloginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlogin
     *
     * @mbg.generated Mon Apr 15 15:00:47 CST 2019
     */
    int updateByExample(@Param("record") Userlogin record, @Param("example") UserloginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlogin
     *
     * @mbg.generated Mon Apr 15 15:00:47 CST 2019
     */
    int updateByPrimaryKeySelective(Userlogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlogin
     *
     * @mbg.generated Mon Apr 15 15:00:47 CST 2019
     */
    int updateByPrimaryKey(Userlogin record);
}