package com.course.pojo;

import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class Course {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.cid
     *
     * @mbg.generated Tue May 07 01:00:07 CST 2019
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.courseName
     *
     * @mbg.generated Tue May 07 01:00:07 CST 2019
     */
    private String coursename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.tid
     *
     * @mbg.generated Tue May 07 01:00:07 CST 2019
     */
    private Integer tid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.message
     *
     * @mbg.generated Tue May 07 01:00:07 CST 2019
     */
    private String message;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.selectedNum
     *
     * @mbg.generated Tue May 07 01:00:07 CST 2019
     */
    private Integer selectednum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.maxNum
     *
     * @mbg.generated Tue May 07 01:00:07 CST 2019
     */
    private Integer maxnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.status
     *
     * @mbg.generated Tue May 07 01:00:07 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.beginTime
     *
     * @mbg.generated Tue May 07 01:00:07 CST 2019
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date begintime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.endTime
     *
     * @mbg.generated Tue May 07 01:00:07 CST 2019
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date endtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.credit
     *
     * @mbg.generated Tue May 07 01:00:07 CST 2019
     */
    private Integer credit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.hours
     *
     * @mbg.generated Tue May 07 01:00:07 CST 2019
     */
    private Integer hours;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.category
     *
     * @mbg.generated Tue May 07 01:00:07 CST 2019
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.departmentID
     *
     * @mbg.generated Tue May 07 01:00:07 CST 2019
     */
    private String departmentid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.cid
     *
     * @return the value of course.cid
     *
     * @mbg.generated Tue May 07 01:00:07 CST 2019
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.cid
     *
     * @param cid the value for course.cid
     *
     * @mbg.generated Tue May 07 01:00:07 CST 2019
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.courseName
     *
     * @return the value of course.courseName
     *
     * @mbg.generated Tue May 07 01:00:07 CST 2019
     */
    public String getCoursename() {
        return coursename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.courseName
     *
     * @param coursename the value for course.courseName
     *
     * @mbg.generated Tue May 07 01:00:07 CST 2019
     */
    public void setCoursename(String coursename) {
        this.coursename = coursename == null ? null : coursename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.tid
     *
     * @return the value of course.tid
     *
     * @mbg.generated Tue May 07 01:00:07 CST 2019
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.tid
     *
     * @param tid the value for course.tid
     *
     * @mbg.generated Tue May 07 01:00:07 CST 2019
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.message
     *
     * @return the value of course.message
     *
     * @mbg.generated Tue May 07 01:00:07 CST 2019
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.message
     *
     * @param message the value for course.message
     *
     * @mbg.generated Tue May 07 01:00:07 CST 2019
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.selectedNum
     *
     * @return the value of course.selectedNum
     *
     * @mbg.generated Tue May 07 01:00:07 CST 2019
     */
    public Integer getSelectednum() {
        return selectednum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.selectedNum
     *
     * @param selectednum the value for course.selectedNum
     *
     * @mbg.generated Tue May 07 01:00:07 CST 2019
     */
    public void setSelectednum(Integer selectednum) {
        this.selectednum = selectednum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.maxNum
     *
     * @return the value of course.maxNum
     *
     * @mbg.generated Tue May 07 01:00:07 CST 2019
     */
    public Integer getMaxnum() {
        return maxnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.maxNum
     *
     * @param maxnum the value for course.maxNum
     *
     * @mbg.generated Tue May 07 01:00:07 CST 2019
     */
    public void setMaxnum(Integer maxnum) {
        this.maxnum = maxnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.status
     *
     * @return the value of course.status
     *
     * @mbg.generated Tue May 07 01:00:07 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.status
     *
     * @param status the value for course.status
     *
     * @mbg.generated Tue May 07 01:00:07 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.beginTime
     *
     * @return the value of course.beginTime
     *
     * @mbg.generated Tue May 07 01:00:07 CST 2019
     */
    public Date getBegintime() {
        return begintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.beginTime
     *
     * @param begintime the value for course.beginTime
     *
     * @mbg.generated Tue May 07 01:00:07 CST 2019
     */
    public void setBegintime(Date begintime) {
        this.begintime = begintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.endTime
     *
     * @return the value of course.endTime
     *
     * @mbg.generated Tue May 07 01:00:07 CST 2019
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.endTime
     *
     * @param endtime the value for course.endTime
     *
     * @mbg.generated Tue May 07 01:00:07 CST 2019
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.credit
     *
     * @return the value of course.credit
     *
     * @mbg.generated Tue May 07 01:00:07 CST 2019
     */
    public Integer getCredit() {
        return credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.credit
     *
     * @param credit the value for course.credit
     *
     * @mbg.generated Tue May 07 01:00:07 CST 2019
     */
    public void setCredit(Integer credit) {
        this.credit = credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.hours
     *
     * @return the value of course.hours
     *
     * @mbg.generated Tue May 07 01:00:07 CST 2019
     */
    public Integer getHours() {
        return hours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.hours
     *
     * @param hours the value for course.hours
     *
     * @mbg.generated Tue May 07 01:00:07 CST 2019
     */
    public void setHours(Integer hours) {
        this.hours = hours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.category
     *
     * @return the value of course.category
     *
     * @mbg.generated Tue May 07 01:00:07 CST 2019
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.category
     *
     * @param category the value for course.category
     *
     * @mbg.generated Tue May 07 01:00:07 CST 2019
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.departmentID
     *
     * @return the value of course.departmentID
     *
     * @mbg.generated Tue May 07 01:00:07 CST 2019
     */
    public String getDepartmentid() {
        return departmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.departmentID
     *
     * @param departmentid the value for course.departmentID
     *
     * @mbg.generated Tue May 07 01:00:07 CST 2019
     */
    public void setDepartmentid(String departmentid) {
        this.departmentid = departmentid == null ? null : departmentid.trim();
    }

    @Override
    public String toString() {
        return "Course{" +
                "cid=" + cid +
                ", coursename='" + coursename + '\'' +
                ", tid=" + tid +
                ", message='" + message + '\'' +
                ", selectednum=" + selectednum +
                ", maxnum=" + maxnum +
                ", status=" + status +
                ", begintime=" + begintime +
                ", endtime=" + endtime +
                ", credit=" + credit +
                ", hours=" + hours +
                ", category='" + category + '\'' +
                ", departmentid='" + departmentid + '\'' +
                '}';
    }
}