package com.course.pojo;

public class Privilege {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column privilege.id
     *
     * @mbg.generated Fri Apr 05 23:30:20 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column privilege.privilegeName
     *
     * @mbg.generated Fri Apr 05 23:30:20 CST 2019
     */
    private String privilegename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column privilege.id
     *
     * @return the value of privilege.id
     *
     * @mbg.generated Fri Apr 05 23:30:20 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column privilege.id
     *
     * @param id the value for privilege.id
     *
     * @mbg.generated Fri Apr 05 23:30:20 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column privilege.privilegeName
     *
     * @return the value of privilege.privilegeName
     *
     * @mbg.generated Fri Apr 05 23:30:20 CST 2019
     */
    public String getPrivilegename() {
        return privilegename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column privilege.privilegeName
     *
     * @param privilegename the value for privilege.privilegeName
     *
     * @mbg.generated Fri Apr 05 23:30:20 CST 2019
     */
    public void setPrivilegename(String privilegename) {
        this.privilegename = privilegename == null ? null : privilegename.trim();
    }
}