package com.course.pojo;

public class RolPriv {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rol_priv.id
     *
     * @mbg.generated Fri Apr 05 23:30:20 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rol_priv.rol_id
     *
     * @mbg.generated Fri Apr 05 23:30:20 CST 2019
     */
    private Integer rolId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rol_priv.priv_id
     *
     * @mbg.generated Fri Apr 05 23:30:20 CST 2019
     */
    private Integer privId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rol_priv.id
     *
     * @return the value of rol_priv.id
     *
     * @mbg.generated Fri Apr 05 23:30:20 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rol_priv.id
     *
     * @param id the value for rol_priv.id
     *
     * @mbg.generated Fri Apr 05 23:30:20 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rol_priv.rol_id
     *
     * @return the value of rol_priv.rol_id
     *
     * @mbg.generated Fri Apr 05 23:30:20 CST 2019
     */
    public Integer getRolId() {
        return rolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rol_priv.rol_id
     *
     * @param rolId the value for rol_priv.rol_id
     *
     * @mbg.generated Fri Apr 05 23:30:20 CST 2019
     */
    public void setRolId(Integer rolId) {
        this.rolId = rolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rol_priv.priv_id
     *
     * @return the value of rol_priv.priv_id
     *
     * @mbg.generated Fri Apr 05 23:30:20 CST 2019
     */
    public Integer getPrivId() {
        return privId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rol_priv.priv_id
     *
     * @param privId the value for rol_priv.priv_id
     *
     * @mbg.generated Fri Apr 05 23:30:20 CST 2019
     */
    public void setPrivId(Integer privId) {
        this.privId = privId;
    }
}