package com.course.pojo;

public class StudentRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_role.id
     *
     * @mbg.generated Fri Apr 05 23:30:20 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_role.stu_id
     *
     * @mbg.generated Fri Apr 05 23:30:20 CST 2019
     */
    private Integer stuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_role.rol_id
     *
     * @mbg.generated Fri Apr 05 23:30:20 CST 2019
     */
    private Integer rolId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_role.id
     *
     * @return the value of student_role.id
     *
     * @mbg.generated Fri Apr 05 23:30:20 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_role.id
     *
     * @param id the value for student_role.id
     *
     * @mbg.generated Fri Apr 05 23:30:20 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_role.stu_id
     *
     * @return the value of student_role.stu_id
     *
     * @mbg.generated Fri Apr 05 23:30:20 CST 2019
     */
    public Integer getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_role.stu_id
     *
     * @param stuId the value for student_role.stu_id
     *
     * @mbg.generated Fri Apr 05 23:30:20 CST 2019
     */
    public void setStuId(Integer stuId) {
        this.stuId = stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_role.rol_id
     *
     * @return the value of student_role.rol_id
     *
     * @mbg.generated Fri Apr 05 23:30:20 CST 2019
     */
    public Integer getRolId() {
        return rolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_role.rol_id
     *
     * @param rolId the value for student_role.rol_id
     *
     * @mbg.generated Fri Apr 05 23:30:20 CST 2019
     */
    public void setRolId(Integer rolId) {
        this.rolId = rolId;
    }
}