package com.course.pojo;

public class StudentCourse {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_course.studentId
     *
     * @mbg.generated Fri Apr 05 23:30:20 CST 2019
     */
    private Integer studentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_course.courseId
     *
     * @mbg.generated Fri Apr 05 23:30:20 CST 2019
     */
    private Integer courseid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_course.score
     *
     * @mbg.generated Fri Apr 05 23:30:20 CST 2019
     */
    private Integer score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_course.studentId
     *
     * @return the value of student_course.studentId
     *
     * @mbg.generated Fri Apr 05 23:30:20 CST 2019
     */
    public Integer getStudentid() {
        return studentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_course.studentId
     *
     * @param studentid the value for student_course.studentId
     *
     * @mbg.generated Fri Apr 05 23:30:20 CST 2019
     */
    public void setStudentid(Integer studentid) {
        this.studentid = studentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_course.courseId
     *
     * @return the value of student_course.courseId
     *
     * @mbg.generated Fri Apr 05 23:30:20 CST 2019
     */
    public Integer getCourseid() {
        return courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_course.courseId
     *
     * @param courseid the value for student_course.courseId
     *
     * @mbg.generated Fri Apr 05 23:30:20 CST 2019
     */
    public void setCourseid(Integer courseid) {
        this.courseid = courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_course.score
     *
     * @return the value of student_course.score
     *
     * @mbg.generated Fri Apr 05 23:30:20 CST 2019
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_course.score
     *
     * @param score the value for student_course.score
     *
     * @mbg.generated Fri Apr 05 23:30:20 CST 2019
     */
    public void setScore(Integer score) {
        this.score = score;
    }
}