package com.course.pojo;

public class Userlogin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userlogin.id
     *
     * @mbg.generated Mon Apr 15 15:00:47 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userlogin.userName
     *
     * @mbg.generated Mon Apr 15 15:00:47 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userlogin.password
     *
     * @mbg.generated Mon Apr 15 15:00:47 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userlogin.userId
     *
     * @mbg.generated Mon Apr 15 15:00:47 CST 2019
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userlogin.role
     *
     * @mbg.generated Mon Apr 15 15:00:47 CST 2019
     */
    private Integer role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userlogin.salt
     *
     * @mbg.generated Mon Apr 15 15:00:47 CST 2019
     */
    private String salt;

    public Userlogin(){}

    public Userlogin(String username, String password) {
        this.username = username;
        this.password = password;
    }

    public Userlogin(Integer id, String username, String password, Integer userid, Integer role, String salt) {
        this.id = id;
        this.username = username;
        this.password = password;
        this.userid = userid;
        this.role = role;
        this.salt = salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userlogin.id
     *
     * @return the value of userlogin.id
     *
     * @mbg.generated Mon Apr 15 15:00:47 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userlogin.id
     *
     * @param id the value for userlogin.id
     *
     * @mbg.generated Mon Apr 15 15:00:47 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userlogin.userName
     *
     * @return the value of userlogin.userName
     *
     * @mbg.generated Mon Apr 15 15:00:47 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userlogin.userName
     *
     * @param username the value for userlogin.userName
     *
     * @mbg.generated Mon Apr 15 15:00:47 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userlogin.password
     *
     * @return the value of userlogin.password
     *
     * @mbg.generated Mon Apr 15 15:00:47 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userlogin.password
     *
     * @param password the value for userlogin.password
     *
     * @mbg.generated Mon Apr 15 15:00:47 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userlogin.userId
     *
     * @return the value of userlogin.userId
     *
     * @mbg.generated Mon Apr 15 15:00:47 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userlogin.userId
     *
     * @param userid the value for userlogin.userId
     *
     * @mbg.generated Mon Apr 15 15:00:47 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userlogin.role
     *
     * @return the value of userlogin.role
     *
     * @mbg.generated Mon Apr 15 15:00:47 CST 2019
     */
    public Integer getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userlogin.role
     *
     * @param role the value for userlogin.role
     *
     * @mbg.generated Mon Apr 15 15:00:47 CST 2019
     */
    public void setRole(Integer role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userlogin.salt
     *
     * @return the value of userlogin.salt
     *
     * @mbg.generated Mon Apr 15 15:00:47 CST 2019
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userlogin.salt
     *
     * @param salt the value for userlogin.salt
     *
     * @mbg.generated Mon Apr 15 15:00:47 CST 2019
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    public String getCredentialsSalt() {
        return username + salt;
    }
}